version: "3.7"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  pastebnn:
    image: evanofslack/pastebnn:0.1.0
    environment:
      PASTEBNN_STORAGE_BACKEND: "redis"
      PASTEBNN_REDIS_HOST: "redis"
      PASTEBNN_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    restart: unless-stopped
