---
version: "3.7"
services:
    pastebnn:
        image: evanofslack/pastebnn:0.1.1
        environment:
            APP_PORT: 5000
            APP_REMOTE_URL: "bin.eslack.net"
        ports:
            - "5000:5000"