# stage build
FROM node:16-alpine as builder

WORKDIR /app

# copy everything to the container
COPY . .

# clean install all dependencies
RUN npm ci && npm audit fix && npm run build

# stage run
FROM node:16-alpine as app

WORKDIR /app

# copy dependency list
COPY --from=builder /app/package*.json ./

# clean install dependencies, no devDependencies, no prepare script
RUN npm ci --production --ignore-scripts && npm audit fix

# copy built SvelteKit app to /app
COPY --from=builder /app/build ./

EXPOSE 3000
CMD ["node", "index.js"]
